Fix

diff --git a/ci/auto-pr/create_pull_requests b/ci/auto-pr/create_pull_requests
--- a/ci/auto-pr/create_pull_requests
+++ b/ci/auto-pr/create_pull_requests
@@ -3,8 +3,8 @@
 set -e -o pipefail; [[ -n "$DEBUG" ]] && set -x
 
 if [[ $# -lt 5 ]]; then
-    echo "usage: $0 pull_request_id pull_request_url pull_request_title commit_sha assignee branches"
-    exit 1
+		echo "usage: $0 pull_request_id pull_request_url pull_request_title commit_sha assignee branches"
+		exit 1
 fi
 
 pull_request_id=$1
@@ -20,66 +20,66 @@ shift
 branches=("$@")
 
 function main(){
-  # Use the author info of the original Git commit
-  git config --global user.email $(git show -s --format='%ae' $commit_sha)
-  git config --global user.name $(git show -s --format='%an' $commit_sha)
+	# Use the author info of the original Git commit
+	git config --global user.email $(git show -s --format='%ae' $commit_sha)
+	git config --global user.name $(git show -s --format='%an' $commit_sha)
 
-  git fetch origin
+	git fetch origin
 
-  # Create PRs based on the target support branches and release branches
-  for branch in ${branches[@]}; do
-    new_branch="$branch-pull-$pull_request_id"
+	# Create PRs based on the target support branches and release branches
+	for branch in ${branches[@]}; do
+		new_branch="$branch-pull-$pull_request_id"
 
-    # Create a new temp branch, push it and create a PR for the change.
-    # But create an issue if anything fails.
-    cherry_pick_and_create_pull_request $branch $new_branch || create_issue $branch
-  done
+		# Create a new temp branch, push it and create a PR for the change.
+		# But create an issue if anything fails.
+		cherry_pick_and_create_pull_request $branch $new_branch || create_issue $branch
+	done
 }
 
 function cherry_pick_and_create_pull_request () {
-  local branch=$1
-  local new_branch=$2
+	local branch=$1
+	local new_branch=$2
 
-  # Cleanup just in case
-  git checkout .
-  git clean -f
+	# Cleanup just in case
+	git checkout .
+	git clean -f
 
-  git checkout $branch
-  git checkout -b $new_branch
-  if git cherry-pick --no-rerere-autoupdate -m1 $commit_sha;
-  then
-    # If the cherry-pick succeeds, creates the backport PR with it
-    git push origin $new_branch
-    git status
-    local pr_body=$(get_successfull_backport_pr_body pr_body $branch)
-    create_pr $branch $local pr_body
-  else
-    # If the cherry-pick fails, creates backport PR draft containing an empty commit
-   git cherry-pick --abort
-   git commit --allow-empty -m "Empty commit [skip ci]"
-   git push origin $new_branch
-   git status
-   local pr_body=$(get_failed_backport_pr_body $branch)
-   create_pr $branch $pr_body --draft
-  fi
+	git checkout $branch
+	git checkout -b $new_branch
+	if git cherry-pick --no-rerere-autoupdate -m1 $commit_sha;
+	then
+		# If the cherry-pick succeeds, creates the backport PR with it
+		git push origin $new_branch
+		git status
+		local pr_body=$(get_successfull_backport_pr_body pr_body $branch)
+		create_pr $branch $local pr_body
+	else
+		# If the cherry-pick fails, creates backport PR draft containing an empty commit
+	 git cherry-pick --abort
+	 git commit --allow-empty -m "Empty commit [skip ci]"
+	 git push origin $new_branch
+	 git status
+	 local pr_body=$(get_failed_backport_pr_body $branch)
+	 create_pr $branch $pr_body --draft
+	fi
 }
 
 function create_pr(){
-  local branch=$1
-  shift
-  local body=$2
-  shift
-  local other_options=$@
+	local branch=$1
+	shift
+	local body=$2
+	shift
+	local other_options=$@
 
-  gh pr create --assignee $assignee \
-         --base "$branch" \
-         --title "Backport to branch($branch) : $pull_request_title" \
-         --body $body \
-         $other_options
+	gh pr create --assignee $assignee \
+				 --base "$branch" \
+				 --title "Backport to branch($branch) : $pull_request_title" \
+				 --body $body \
+				 $other_options
 }
 
 function get_successfull_backport_pr_body() {
-  local branch=$1
+	local branch=$1
 
 	body=$(cat <<-END
 	This is an automated backport of the following commit:
@@ -92,13 +92,13 @@ function get_successfull_backport_pr_body() {
 	END
 	)
 
-  echo "${body}"
+	echo "${body}"
 }
 
 function get_failed_backport_pr_body() {
-  local branch=$1
+	local branch=$1
 
-  body=$(cat <<-END
+	body=$(cat <<-END
 	This is an automated request for a manual backport of the following commit:
 
 	- Original PR: $pull_request_url
@@ -118,15 +118,15 @@ function get_failed_backport_pr_body() {
 	END
 	)
 
-  echo "${body}"
+	echo "${body}"
 }
 
 function create_issue () {
-  local branch=$1
+	local branch=$1
 
-  gh issue create --assignee $assignee \
-    --title "Backport to branch($branch) failed: $pull_request_title" \
-    --body "Backport of $pull_request_url for commit $commit_sha to branch($branch) failed"
+	gh issue create --assignee $assignee \
+		--title "Backport to branch($branch) failed: $pull_request_title" \
+		--body "Backport of $pull_request_url for commit $commit_sha to branch($branch) failed"
 }
 
 main
